# Generated by Django 5.1.7 on 2025-03-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitytype',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='entitytype',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
