# Generated by Django 5.1.7 on 2025-03-23 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_entitytype_options_entitytype_sort_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitytype',
            options={},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='status',
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='api.entitytype'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_types', to='api.campaign'),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
