# Generated by Django 5.1.7 on 2025-03-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_relationship_reverse_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entity_images/'),
        ),
        migrations.AddField(
            model_name='entity',
            name='stats',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entitytype',
            name='components',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
