# Generated by Django 5.1.7 on 2025-03-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_entity_image_entity_stats_entitytype_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='token_image',
            field=models.ImageField(blank=True, null=True, upload_to='entity_tokens/'),
        ),
    ]
