# Generated by Django 5.1.7 on 2025-03-25 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_entity_token_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='entitytype',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='campaign',
        ),
        migrations.AddField(
            model_name='entity',
            name='campaign',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='api.campaign',
                null=True,  # Allow null initially to avoid data issues
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name='entity',
            name='dnd_beyond_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='reverse_description',
            field=models.TextField(blank=True),
        ),
    ]